### ISSUE TITLE
failed to create containerd task

### ISSUE THREAD

**Issue by joshuacox** [go-skynet/helm-charts#39]
When installing localai via the helm chart I get this error:

```
 Warning  Failed            49m (x5 over 51m)     kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: requirement error: invalid expression: unknown
```

I have the [gpu-operator](https://github.com/NVIDIA/gpu-operator) installed and running.

And I can run this gpu-pod succesfully:

```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
```

```
k logs gpu-pod                  
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

Why won't the localAI pod run?
